local config = {
	name = "Glock",
	automatic = false,
	fire_rate = 280,

	magazine_size = 17,
	reserve_ammo = math.huge,
	tactical_reload_time = 1.75,

	damage = 15,
	headshot_multiplier = 5,
	limb_multiplier = 1.5,
	damage_falloff_start = 55,
	damage_falloff_end = 210,
	minimum_damage_multiplier = 0.48,

	muzzle_velocity = 620,
	gravity = Vector3.new(0, -55, 0),
	max_distance = 360,

	spread_hip = 2.1,
	spread_aim = 0.14,
	spread_per_shot = 0.14,
	spread_max = 3.2,
	spread_recovery = 9.5,

	recoil_pitch = 1.25,
	recoil_yaw = 0.62,
	recoil_roll = 0.28,
	recoil_snap_speed = 32,
	recoil_aim_multiplier = 0.58,

	recoil_camera_pitch = 1.4,
	recoil_camera_yaw = 0.35,
	recoil_camera_roll = 0.08,

	recoil_camera_direct = 0.008,
	recoil_camera_horizontal_direct = 0,
	recoil_camera_horizontal_speed = 16,

	recoil_camera_smoothness = 0.95,
	recoil_camera_impulse = 0.9,
	recoil_camera_velocity_damping = 8,
	recoil_camera_recovery_frequency = 10,
	recoil_camera_recovery_damping = 0.9,
	recoil_camera_max_angle = 3.5,

	recoil_manual_pull_strength = 1.15,
	recoil_manual_pull_deadzone = 0.35,

	recoil_viewmodel_kickback = 0.1,
	recoil_viewmodel_rise = 0.01,
	recoil_viewmodel_side = 0.012,

	recoil_viewmodel_climb = 5,
	recoil_viewmodel_pitch = 5.2,
	recoil_viewmodel_yaw = 0.55,
	recoil_viewmodel_roll = 0.7,

	recoil_viewmodel_direct = 0.28,
	recoil_viewmodel_smoothness = 0.78,
	recoil_viewmodel_impulse = 8,
	recoil_viewmodel_punch_direct = 0.11,
	recoil_tip_pivot_multiplier = 0.68,
	recoil_arm_pitch_multiplier = 0.62,
	recoil_arm_yaw_multiplier = 0.38,
	recoil_arm_roll_multiplier = 0.5,
	recoil_support_arm_multiplier = 0.8,
	recoil_arm_ads_multiplier = 0.65,

	recoil_viewmodel_reset_frequency = 8,
	recoil_viewmodel_reset_damping = 0.55,

	recoil_viewmodel_recovery_frequency = 4.3,
	recoil_viewmodel_recovery_damping = 0.48,
	recoil_viewmodel_position_recovery_frequency = 4.8,
	recoil_viewmodel_position_recovery_damping = 0.52,

	recoil_rise_speed = 10,

	recoil_arms_push_out = 0.055,
	recoil_arms_push_out_impulse = 6.5,
	recoil_arms_push_out_max = 0.16,

	recoil_ads_visual_multiplier = 0.62,
	recoil_ads_position_multiplier = 0.24,
	recoil_ads_arms_push_multiplier = 0.14,
	recoil_ads_tip_pivot_multiplier = 0.34,

	screen_shake_pitch = 3.2,
	screen_shake_yaw = 1.4,
	screen_shake_roll = 0.65,
	screen_shake_min = 0.55,
	screen_shake_impulse = 30,
	screen_shake_frequency = 15,
	screen_shake_damping = 0.82,
	screen_shake_max_angle = 4,

	recoil_viewmodel_max_offset = 0.11,
	recoil_viewmodel_max_angle = 14,

	camera_bob_enabled = true,
	camera_idle_bob_amount = 0.003,
	camera_idle_bob_speed = 0.82,
	camera_idle_pitch = 0.03,
	camera_idle_side_multiplier = 0.18,
	camera_walk_bob_amount = 0.045,
	camera_walk_bob_speed = 8.5,
	camera_walk_pitch = 0.16,
	camera_walk_roll = 0.32,
	camera_bob_walk_speed = 14,
	camera_bob_smoothing = 12,
	camera_sprint_bob_amount_multiplier = 0.65,
	camera_sprint_bob_speed_multiplier = 1.12,
	camera_sprint_bob_side_multiplier = 0.3,
	camera_sprint_bob_smoothing = 7,

	sway_amount = 1.15,
	sway_horizontal_amount = 1.6,
	ads_sway_stability = 0.22,
	ads_movement_stability = 0.1,
	sway_speed = 12,
	sway_limit = 5.5,

	procedural_enabled = true,
	procedural_idle_amount = 0.018,
	procedural_idle_speed = 0.82,
	procedural_idle_pitch = 0.12,
	procedural_idle_yaw = 0.08,
	procedural_walk_amount = 0.045,
	procedural_walk_bob_speed = 8.5,
	procedural_walk_roll = 0.35,
	procedural_walk_speed = 14,
	procedural_move_smoothing = 11,
	directional_tilt_pitch = 1.2,
	directional_tilt_yaw = 0.7,
	directional_tilt_roll = 2.4,
	directional_tilt_smoothing = 10,
	directional_tilt_sprint_multiplier = 1.35,
	directional_tilt_ads_multiplier = 0.3,
	procedural_ads_breath_amount = 0.0025,
	procedural_ads_breath_speed = 0.42,
	procedural_ads_breath_pitch = 0.025,
	procedural_ads_breath_yaw = 0.015,
	procedural_ads_breath_roll = 0.02,
	procedural_ads_locked_amount = 0,
	procedural_ads_turn_limit = 0.08,
	procedural_ads_turn_pitch = 0.015,
	procedural_ads_turn_yaw = 0.02,
	procedural_ads_turn_roll = 0.025,
	procedural_ads_recoil_roll = 0.04,

	position_offset = Vector3.new(0, 0, 3),
	aim_position_offset = Vector3.new(0, 0, 3.05),
	body_camera_ads_viewmodel_offset = Vector3.new(0.1, -0.26, 0.4),
	body_camera_ads_rotation = Vector3.new(-0.7, 1.6, -0.45),
	ads_sight_y_offset = 0.015,
	rotation_offset = Vector3.new(0, 0, 0),

	aim_speed = 2,
	aim_spring_frequency = 1.7,
	aim_spring_damping = 0.96,

	aim_transition_side = -0.08,
	aim_transition_lift = 0.02,
	aim_transition_push = 0,
	aim_transition_pullback = 0.04,
	aim_transition_pitch = -0.35,
	aim_transition_yaw = 0.8,
	aim_transition_roll = -0.7,

	ads_alignment_follow_speed = 20,

	aim_fov = 62,
	default_fov = 70,

	idle_fade_time = 0.18,
	idle_resume_fade_time = 0.2,
	idle_speed = 1,

	main_c0 = CFrame.new(0.445, -1, -5.683) * CFrame.Angles(0, math.rad(-180), 0),
	main_c1 = CFrame.identity,
}
return config


